language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2
env:
  global:
    - CODECLIMATE_REPO_TOKEN=0a29827fa48b1236e7c27bf9948e3ee3cb05d50630a2896014edd7b7bbf616a2
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c696eaa01bc1bae73cb2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
